### ISSUE TITLE
Work ony with some file

### ISSUE THREAD

**Issue by amerigomancini** [djomlastic/vlc-prev-next#2]
Thank you for the tool.
I notice that sometime , with some file will not work. Is not about the fileextension, seems to choose when to work randomly. I'm a caveman on computer but.. you have some sudjestion?

Thank you!

**Comment by djomlastic** [comment]
Could you provide some information (operating system, Vlc player version)? Also, once you start Vlc, hit Ctrl + M on the keyboard. It will bring up the "messages" console. In the lower left corner switch Verbosity to 2 (debug), and in the Filter field type "lua". Look for messages starting with "[VlcPrevNext]" (with square brackets) and any errors/warnings.
