### ISSUE TITLE
Directory issue

### ISSUE THREAD

**Issue by sayand0122** [djomlastic/vlc-prev-next#3]
The directories you mentioned for linux, I dont have any such directory available?

any help for that?

**Comment by djomlastic** [comment]
Which Linux distribution? The `~/.local` is a hidden directory within your home directory. Also if some folder along that path is not there (eg `/lua/extensions`), you might need to create it.

**Comment by sayand0122** [comment]
I am using ubuntu 20.04 and as you said about the extensions i can go as far as ```/.local/share/``` after that i dont have anything like ```vlc/lua/extensions```

Do you think i should create that?

Moreover what do you think should i use, **linux (single user)** or **linux (all user)** like if I am creating that path?

**Comment by djomlastic** [comment]
Go ahead and create directories, nothing bad can happen. I use it for my user only (single user), but that depends on your personal preferences regarding your system.

**Comment by sayand0122** [comment]
Yup thanks it works fine. Only thing is we have to check the play next and previous every time we start vlc but i guess that's OK.

got another thing but i guess it's not related to this technical stuff, my vlc plays ep 10 after it completed ep 1... kinda silly to ask. :-)

Anyways my issue is resolved and thank you so much for helping

**Comment by djomlastic** [comment]
> Only thing is we have to check the play next and previous every time we start vlc

That's how vlc player handles extensions. The best you can do is `Tools>Preferences>Interface` and check `use only one instance when started from file manager`.

> my vlc plays ep 10 after it completed ep 1...

It may seem weird, but alphabetical order is: ep_1, ep_10, ep_2. Names should use a leading zero if there are 10+ files, so: ep_01, ep_02, ... ep_10.

**Comment by sayand0122** [comment]
Thanks pal !!!
